version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v

  race:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v -count 500 -race

workflows:
  version: 2
  build:
    jobs:
      - build
      - race
