version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v

  races:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v -race

workflows:
  version: 2
  build:
    jobs:
      - build
      - races
