version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v

  race:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: GORACE="halt_on_error=1" go test ./... -count 1000 -race

workflows:
  version: 2
  build:
    jobs:
      - build
      - race
