version: 2
jobs:
  build-go-modules:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./... -v

workflows:
  version: 2
  build:
    jobs:
      - build-go-modules
      - build-vendoring
